apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  template:
    spec:
      containers:
        - name: logoutput-container
          image: prachishah0105-ai/log-output:v2
          # --- ADD THIS ---
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
          # ----------------
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3000
  initialDelaySeconds: 20 # We wait longer to let Ping-pong start first
  periodSeconds: 5
        - name: log-output
          image: <your-docker-hub-username>/log-output:v1.0
