apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml # Ensure this points to your actual deployment file
  - manifests/service.yaml    # Ensure this points to your actual service file
