apiVersion: v1
kind: ConfigMap
metadata:
  name: project-config
  namespace: project # Ensure this matches your Exercise 2.4 namespace
data:
  BACKEND_URL: "http://todo-backend-svc:2345"
  PORT: "3000"
