apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-image-claim
spec:
  storageClassName: local-storage # Uses the same PV setup from 1.11
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
