apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app # This MUST match the label in your deployment.yaml
  ports:
    - nodePort: 30080 # This port is opened on your k3d nodes
      protocol: TCP
      port: 1234      # This port is used inside the cluster
      targetPort: 3000 # This is the port your app listens on
