apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/broadcaster-dep.yaml
images:
  - name: TODO_BACKEND_IMAGE
    newName: prachishah0105-ai/todo-backend
    newTag: latest # GitHub Actions will update this automatically
