apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  template:
    spec:
      containers:
      readinessProbe:
  httpGet:
    path: /healthz
    port: 3000 # Matches the PORT variable in your code
  initialDelaySeconds: 15
  periodSeconds: 5
        - name: todo-backend
          image: prachishah0105/todo-backend:v1.1
          envFrom:
            - configMapRef:
                name: project-config
env:
  - name: DATABASE_URL
    value: "postgres://postgres:todo-password@postgres-svc:5432/postgres"
