apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  template:
    spec:
      containers:
        - name: todo-backend
          image: prachishah0105/todo-backend:v1.1
          envFrom:
            - configMapRef:
                name: project-config
env:
  - name: DATABASE_URL
    value: "postgres://postgres:todo-password@postgres-svc:5432/postgres"
